- apps/verify/behaviours/email-lookup-sender.js
Bug: sometimes hof adds `?hof-cookie` when you click on a link.  This means that this will be added to req.query.token.  Therefore, it won't find this in the redis db. Adding `&` will separate out this from the query string
> Fix: Pass in `&` as part of the link sent with the token

- Dockerfile
* On acp, the `wkhtmltopdf` failed for a weird reason.  `Error: QPainter::begin(): Returned false`.  It appears that it could be to do with the setup or not having all the required dependencies
* install the dependencies exactly how they are set up for EVW, another service on ACP using this package
* We `wkhtmltopdf` to convert our html to pdf
> MS-755 - Docker - wkhtmltopdf - install more dependencies

- Dockerfile
- config.js
* PDF generation was not working because of permissions. When running on ACP, the user is nodejs not root.  Therefore, give access of the public folder to nodejs user which is set to 999 and the group 998
* Also set the temp location to the proper public area
> MS-755-PDF: Change public folder permissions

- docker-compose.yml
In ACP, the containers are run as nodejs user NOT as root.  Therefore, run it locally how it will run on ACP
> Docker-compose: Run as nodejs user

- apps/pdf/util/pdf-generator.js
- test/unit/pdf/behaviours/generate-send-pdf.test.js
- test/unit/pdf/util/pdf-generator.test.js
* chai-as-promise always requires `return expect`
* yields: calls the callback with arguments provided, if no args just call the callback
> MS-756 - PDF generator - Fix unit tests

- .drone.yml
Seems unnecessary as we already have something else that gets built for PR, build_app
> Drone - remove PR build

- .drone.yml
It currently runs it twice which is unnecessary and time consuming
> Fix: Get drone to run 1 status build

- .drone.yml
- README.md
- Aim is to save time
- Every PR has two builds, once when you push and another time when you create a PR
- Only run the unit tests for the push to a branch
- Only run acceptance tests for pushes into a PR
Note: this might not work so I'll have to test it
> Drone: Don't run acceptance test on branch unless PR

- apps/nrm/views/partials/summary-table-potential-victim.html
Fixed check your answer - Home Office Reference displays no information
If the user has not entered does-pv-have-children question then they will not need to see this answer.
another way of saying they have not gone down the duty to notify user journey.
> MS-942: fix: update summary-table-potential-victim.html

- browsers/chrome/Dockerfile
When running acceptance tests we want to allow the installation of google chrome
Chrome version is unstable currently and we will need to seek future alternative.
The version of chrome we use to run puppeteer acceptance tests now flags up a warning when we try to install chrome on docker.
Since this version of chrome is unstable the new rules ( I think, since the tests have been running fine up until today) forces us to either change the chrome browser version we are using or add a ‘--allow-unauthenticated’  command when installing the package.
> Fix: allow chrome browser to be installed

- apps/nrm/translations/src/en/pages.json
- apps/verify/translations/src/en/pages.json
Dev environment adds another heading on top which doesn't happen locally
Therefore used hash to create heading in content pages
> MS-967 task: update heading on dev env

- apps/nrm/translations/src/en/validation.json
- apps/verify/translations/src/en/validation.json
https://jira.digital.homeoffice.gov.uk/browse/MS-1149
Previously, if someone enters a value and it doesn't match what is on the list, then no error message was shown
> MS-1149 Fix add error message when there is no match for typeaheads

- apps/nrm/behaviours/generate-send-pdf.js
- test/unit/nrm/behaviours/generate-send-pdf.test.js
- Remove the functionality added under MS-1099 in the interim release that copies the PDF to the FR.
- Part of - Retain PDF File for go-live implementation
> MS-1214 task: remove FRs from PDF email sent by Notify

- apps/nrm/behaviours/casework-submission.js
- apps/nrm/behaviours/generate-send-pdf.js
- apps/nrm/models/i-casework.js
- apps/nrm/models/submission.js
- config.js
You now need to set an env var of `WRITE_TO_CASEWORK=true` else it will use the default mock backend for casework
I also spotted a few bugs in the code while I was working on this so there are a few fixes in there also
> Disable sending to casework backend by default

- README.md
- config.js
Previously, emails were pointing to the production Modern slavery account.  This meant the following:
* Unnecessary users having access to prod emails
* Analytics not being accurate because of test and also live emails being sent out together
> MS-1369 Point emails to gov notify Modern slavery test

- package-lock.json
- package.json
A newer version of hof adds a readiness check endpoint.
As the readiness check is now required to run in Kubernetes using our
current config, this commit explicitly bumps the version to ensure
compatibility.
> MS-1457 Bump hof version

- apps/common/translations/src/en/validation.json
- apps/common/validators.js
- apps/verify/fields/index.js
- test/unit/common/validators.test.js
The email validation bundled with hof is overly restrictive.
This commit liberalises the validation to essentially accept anything
that has one @ sign and at least one dot in the domain portion of the
address.
A particular problem with the old code is that it wouldn't accept
apostrophes in the username portion; this commit fixes that.
> MS-1507 Liberalise email validation

- apps/verify/views/start.html
> MS-1554 Remove extraneous space from link text

- apps/nrm/translations/src/en/fields.json
Replacement pull request with correct username and email for me.
Corrected 'Not Sure' to 'Not sure'
> MS-1239 Fix capitalisation in "Not Sure"for under 18 question

- apps/nrm/fields/index.js
- apps/nrm/views/content/pv-under-age.md
- apps/nrm/views/partials/pv-under-age-panel-not-sure.html
- apps/nrm/views/partials/pv-under-age-panel-yes.html
- apps/nrm/views/pv-under-age.html
Previously, if you clicked on radio buttons, some content would appear. This failed an accessibility audit as a High issue.  This means we have to resolve it quickly.
> MS-1174 under 18 step: move hidden content to main body

- apps/nrm/views/pv-under-age.html
- assets/scss/app.scss
It's currently unclear which button to click to proceed to the next
page. This commit moves the "save and exit" button to be after the
"continue" button, and colours it grey instead of green.
For more information on secondary buttons, see the GOV.UK Design System:
https://design-system.service.gov.uk/components/button/#secondary-buttons
The concept of secondary buttons did not exist in GOV.UK Elements, which
hof continues to use. Therefore, this commit also adds some SCSS to
add a .button-secondary class.
> Add secondary button

- package-lock.json
- package.json
I ran `npm audit` on this repo. It fixed several security vulnerabilities in dependencies.
Most dependencies were within semantic versioning tolerance, and were applied in the first commit. A couple required breaking API changes, but our tests still run fine.
An invocation of `npm audit` now reads:
>   7 vulnerabilities require manual review. See the full report for details.
These seven vulnerabilities need to be dealt upstream in `hof`.
> Run npm audit

- package-lock.json
- package.json
Jira Ticket: https://collaboration.homeoffice.gov.uk/jira/browse/SD-94
Linked PR: https://github.com/UKHomeOffice/ms-uk-local-authorities/pull/7
Changes: 
1. ms-uk-local-authorities version update to 2.2.1.
> SD-94: updated ms-uk-local-authorities to 2.2.1

- package-lock.json
- package.json
bump ms-email-domain npm package
This has nccgroup in the list. They've been added to do ITHC
> SD-96 bump ms-email-domain npm package

- package-lock.json
- package.json
Use newer ms-email-domains npm version
This is for ITHC and include more ncc email domains
> SD-96 Update ms-email-domains add more ncc email domains

- apps/verify/behaviours/email-lookup-sender.js
- package.json
Modern slavery sends an email to users with a token to verify the user and then be able to complete the form.  In the new version of HOF, when you click on a link, it brings up a session error page. This PR fixes the above issue
I've also added a script to debug the code in `package.json`
Because a user has clicked on a link they should not be shown a session-error
* The issue is in `hof-form-wizard` and in the `req.path !== first`
`req.path` was returning `/start` but `first` was returning `/start/`
* Remove end slash from the first step in the journey from '/start/'
to `/start`
Locally
> SD-707 Fix session expired from token email

- package-lock.json
- package.json
An update hof-template partials so that the gid cookie is displayed within the cookie policy
The table was missing the "_gid" tracking cookie
-Updated hof-template-partials that includes information on the gid cookie
> SD-642 gid cookie is not mentioned in cookie policy

- apps/nrm/models/submission.js
A change to submission.js to remove '-'
This was affecting the way holidays were calculated if the user selected 'Northern Ireland'
We passed the jurisdiction as 'NORTHERN-IRELAND' when iCasework is looking for 'NORTHERNIRELAND'
changed where the Jurisdiction is set in the iCasework submission to remove '-' 
Will need to be tested in prod
> SD-837 alter submission to icasework for jursidiction

- .drone.yml
- apps/nrm/behaviours/save-and-exit.js
- test/unit/nrm/behaviours/save-and-exit.test.js
**Jira Ticket:** https://collaboration.homeoffice.gov.uk/jira/browse/SD-118
**Changes**
- Changed and refactored save-and-exit.js to include calculation for end date instead of start date on the report.
- Added unit tests (save-and-exit.test.js) for the expiry date calculation. 
- Corrected features to feature typo error in drone.yml
- Tested locally, and end date is now showing start date plus 28 days. 
**Screenshot**
- Today (7 June 2021) plus 28 Days (5 July 2021):
> SD-118: Saving a report shows wrong due date of completion

- package-lock.json
- package.json
Security vulnerability in trim-newlines
Trim-newlines is a child dependency of a package that is no longer maintained
Swapped out old parent package (npm-sass) for currently maintained equivilant (dart-sass)
Have done manual testing - No issues found.
N/A
N/A
> Updated hof-build to remove security tirm-newlines vulnerability

- package-lock.json
- package.json
What
Updated ms-email-domains to 2.2.5
Why
Deleted nccgroup email domains that were used for ITHC and are not required anymore
How
Removed from email domain list
Test
Submitting a work email address to access the service with a deleted email domain will produce an ‘Email not recognised’ error
> Updated ms-email-domains to 2.2.5

- apps/nrm/models/submission.js
NRM-71 prevent duplicate send ExternalId to iCw
This will be used to prevent us from sending duplicate reports to iCW.  Resolver will check if there is an existing ExternalId
locally tested and works fine
> NRM-71 prevent duplicate send ExternalId to iCw

- .gitignore
- acceptance-test/test-config.js
- acceptance-test/user-pathways/happy-path/happy-path.test.js
- apps/common/views/paper-version-download.html
- apps/common/views/start.html
- config.js
- lib/download-file.js
- package.json
- server.js
* When you attempt to download the prompt sheet it comes back as a 404 not found. This is because the code for the file was removed to a lib directory which impacts on the location of the file
* this lib has been removed from the path to address this issue
Locally, I will wait for the branch to be setup before testing
> NRM-91 bugfix download prompt sheet not found error

- kube/icasework/icasework-resolver-deployment.yml
Reduce Icasework resolver replicas to 1
We believe having two resolvers may be causing issues with duplication in production
Reduce replicas to 1 in resolver deployment
> Reduce Icasework resolver replicas to 1

- apps/nrm/translations/src/en/pages.json
- apps/nrm/views/confirmation.html
- kube/icasework/icasework-resolver-deployment.yml
- package.json
- yarn.lock
Scheduled downtime for iCasework resolver with Warning on confirmation page
iCasework is undergoing works this saturday. This will leave all submitted reports in the SQS queue until the resolver is scaled back up at midnight Monday morning.
Add annotation to deployment file to schedule downtime.
Warning added to confirmation page
> Schedule downtime with confirmation page warning

- apps/nrm/translations/src/en/pages.json
- apps/nrm/views/confirmation.html
- kube/icasework/icasework-resolver-deployment.yml
Reverting the scheduled downtime and removing the guidance relating to it
Scheduled downtime has passed and is no longer needed
revert changes to icasework resolver deployment
remove guidance relating to it on confirmation page
> Remove downtime and guidance

- README.md
- config.js
- yarn.lock
- Amended token expiry from 24 hours to 30 minutes.
- Amended  broken link for Gov Notify in ReadMe
- A normal email token for save and return is usually set to a number of minutes e.g. 30 or 60 minutes.
- Link to Gov Notify was incomplete and so was not working
- Amended token expiry in config
- Added 'www' to link in ReadMe
> NRM-127: amend token expiry duration

- package.json
- yarn.lock
**Changes**
- Updated HOF to version 19.13.6, to mitigate validation bug fixes and security vulnerabilities in urijs version 1.19.7. Also to include upgrades to cached-path-relative version 1.1.0, and shell-quote version 1.7.3, to mitigate security errors for browserify version 17.0.0.
- Updated mocha to version 9.2.1 to mitigate vulnerabilties in nanoid v3.1.25.
> NRM-136: Updated HOF and mocha versions in package.json

- package.json
- test/_unit/common/validators.spec.js
- yarn.lock
- Update ms-email-domains package to allow capital letters
- add unit test for capital letters in email domains 
- update hof package  
Users are not able to access the form when they enter capital letters in the domain of their email address.
Amend ms-email-domains package to allow capital letters in domain
Tested locally
> NRM-133: update ms-email-domains to allow capital letters

- apps/nrm/fields/index.js
- apps/nrm/util/filtered-countries.js
Removed UK as one of the overseas options on /where-exploitation-happened-overseas
Request from stakeholder. There is a separate option for the UK, and it does not need to appear in the overseas options
Filter the countries array that was being used to exclude the UK 
Local testing on /nrm/where-exploitation-happened-overseas
> Remove UK from overseas option

- package.json
- yarn.lock
- Update ms-email-domains package
- To add an email domain to the whitelist of allowed domains.
> NRM-143: update ms-email-domains

- README.md
- apps/nrm/behaviours/resume-form-session.js
- apps/nrm/behaviours/save-and-exit.js
- apps/nrm/behaviours/save-form-session.js
- apps/nrm/views/reports.html
- apps/nrm/views/save-and-exit.html
- kube/save-return-data-alerts/deployment.yml
- test/_unit/nrm/behaviours/save-and-exit.spec.js
- Fix the expiry date to be based on when the form was last updated. 
After Shamil approved the changes and Satya tested on the branch.
- On the save and exit page - removed the date argument as the previous one was not passing through a timestamp and the time 'now' is being used which works, as this is when the form was last updated
- Fixed unit test related to changes to the above
- Updated the image of the save and email alerts service
- Currently the expiry date is based on the date the report was created not the date it was last updated, which is what it should be.
- Change the expiry date displayed on the dashboard, and save-and-exit page. Also, altered text on these pages to clarify the changes. 
- Remove the firstAlert property from the report if the form is updated after a 7 day …
> Nrm 139 fix expiry date

- apps/nrm/behaviours/casework-submission.js
- apps/nrm/behaviours/check-email-token.js
- apps/nrm/behaviours/reset-journey-to-submit-nrm.js
- apps/nrm/behaviours/resume-form-session.js
- apps/nrm/behaviours/save-form-session.js
- apps/nrm/models/submission.js
**Changes**	
- Generated External ID at the beginning of the service and added to the session model for logging through the service.
- Adding logs to saving form session, casework submissions, resume and save form sessions.
**Reason**
- Increased logging was required in NRM to check cases were being submitted to the queue, and to log any errors.
- External ID was added to the beginning of the service, so the whole user journey could be tracked through the service and into iCasework via filtering the External ID within openSearch.
**Tests**
- Tested multiple reports through the service and into iCasework where the External ID can be observed. (Screengrab's on Jira Ticket NRM-168: https://collaboration.homeoffice.gov.uk/jira/browse/NRM-167)
> NRM-167: Additional Logging to the Service

- apps/nrm/behaviours/casework-submission.js
- apps/nrm/models/submission.js
**Changes**
- Added a case if the externalID is undefined, a UUID is generated on the submission.js page.
- Changed the casework-submission page to log the case reference with the external ID.
**Reason**
- This is a final check in the data generated for iCasework, that an external ID is present and if not generate one and log submission with this ID.
> NRM-167: Ensuring a UUID is sent to iCasework

- browsers/chrome/Dockerfile
- Dockerfile for chrome browser updated to change google chrome to stable version to mitigate a dependency error 'libu2f-udev' being triggered on the pipeline and acceptance tests not running.
- Acceptance tests not running on pipeline and triggering errors.
- Tested on branch environment and all acceptance tests ran and passed successfully.
> pipeline check

- README.md
- apps/nrm/behaviours/casework-submission.js
- Change Report Reference in Logs to Report ID
- Amend readme links for clarity
- Update yarn.lock
- Report reference in logs could be anything including names which is security risk. Changing to the report id removes this risk.
Changed Report Reference to Report ID in casework submission behaviour
- Tested in branch comparing open search logs
> NRM-182: Change Report Reference in Logs to Report ID

- package.json
- yarn.lock
- Upgraded pg to version 8.9.0 to mitigate Unhandled Promise Rejection Warning showing in opensearch logs
- Tested end to end on branch environment, error is now not displayed
> NRM-223: pg dependency upgrade

- README.md
- apps/nrm/fields/index.js
- apps/nrm/index.js
- Re-added 'what-happened' to the index.js step
- Re-added ' what-happened' field information into 'fields/index.js'
- Updated Readme
- To mitigate the scenario whereby data would be saved in the 'what-happened' field in the save and return feature, and this data would be un-editable and lost if this legacy page was in-accessible.
> NRM-224: Re-instating what happened page and iCasework mapping

- server.js
Add the following CSP rules to service config
imgSrc: [
'www.google-analytics.com',
'ssl.gstatic.com',
'www.google.co.uk/ads/ga-audiences'
],
connectSrc: [
'https://www.google-analytics.com',
'https://region1.google-analytics.com',
'https://region1.analytics.google.com'
]
Support new GA analytics domain from https://region1.analytics.google.com to https://region1.google-analytics.com
> NRM-144: add new CSP rules for GA4

- Dockerfile
-  Added postgres to Dockerfile to install postgres in order to carry out checks as part of Postgres version upgrade  - [HOFF-625](https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-625)
- Before we request ACP to upgrade the postgres database instance from v11.22 to v14.10 for Modern Slavery in the Production Environment we need to connect to the DB to get insights on data. This helps us to verify the integrity of the data in the upgraded DB as part of Data Validation.
-  Added postgres to Dockerfile
- Tested in notprod environment
> HOFF-625: Install postgres for pre-upgrade checks for database in prod

- .drone.yml
- Dockerfile
What?
 I've added Trivy Scanner to Pipeline and removed deprecated Anchore Scanner for the Modern Slavery service, see ticket
`https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-612`
Why?
Trivy will let you scan images, file systems and repositories for any vulnerabilities and issues. It will detect CVEs of OS packages, applications susceptibilities, and exposures of IaC in Terraform files, Kubernetes and Docker. Drawback of Anchore Scanner is it’s significantly slower, the process of using it is more cumbersome, the output is less friendly and most importantly, it scans fewer CVEs. 
How?
 Removed Anchore cve exception file and added trivy cve exception file in hof-services-config repo from Modern Slavery configs. Removed Anchore Scanner steps from pipeline and added trivy scanner …
> HOFF-612: Replace Anchore with Trivy

- .drone.yml
Commented out acceptance tests steps on drone.yml file
To temporary fix the build pipeline.
The error is as follows:
_kubernetes has failed: container failed to start: id=drone-yxdct65qen2v1ldzf5g3 exitcode=2 reason=Error image=340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind:latest_
The puppeteer library is causing the issue, might be unstable versioning available.
The acceptance test is causing delays in merging our PRs to the master.
Since E2E automation test are implemented by QA team, dev team agreed to remove it from development environment.
following instruction on Jira ticket [NRM-296](https://collaboration.homeoffice.gov.uk/jira/browse/NRM-296)
no test required
> NRM-296-remove acceptance tests from builds

- kube/app/deployment.yml
* Skip email function is used to skip the email verification process while using hof test email.
* QA team are unable to progress due to the email verification process in UAT.
* This isn't a temporary change 
- Testers require this feature to assist with their automation scripts. 
- Similar to Branch Env we require to add this feature to UAT env
- Jira link: https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-839
* Add condition to set the env variables to skip when hof email is used
* This feature has been  setup in Branch Env and requires to setup for UAT
* Requested by Dev's and QA team to assist with the automation scripts
We will test the UAT Ingress url to validate the changes once deployed to UAT ENV.
> HOFF-839: Set Env variable for UAT to skip email verification

- .snyk
- kube/icasework/icasework-resolver-deployment.yml
- Medium-security-vulnerability-icasework-resolver-aws-sdk-dependency - [HOFF-731](https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-731) 
icasework-resolver has been updated with security vulnerabilities and needs to be tested in NRM
- In icasework-resolver-deployment.yml image: [quay.io/ukhomeofficedigital/icasework-resolver](http://quay.io/ukhomeofficedigital/icasework-resolver): has been updated
tests passing
> HOFF-731 Fix Medium security vulnerability

- apps/common/behaviours/sanitise-inputs.js
- hof.settings.json
- server.js
- test/_unit/common/sanitse-inputs.spec.js
Fix NRM Live Issue - User getting 504 error when adding square brackets in text area - [NRM-341](https://collaboration.homeoffice.gov.uk/jira/browse/NRM-341)
To fix 504 error where users were not able to progress with their case, a rule was added in the HoF Services Config [PR-341](https://github.com/UKHomeOfficeForms/hof-services-config/commit/8979e2e9f3098ef3d20ea5c4817e38865e9b3534) to enable square brackets and a sanitisation method was configured to run on NRM, which would add a hyphen after the square brackets.
Added a new behaviour to the common directory to configure the sanitisation function to work for NRM. 
tests passing locally and tested on branch
> [NRM 341] configured sanitisation method from HoF to work on NRM

- apps/nrm/behaviours/check-email-token.js
- apps/verify/behaviours/email-lookup-sender.js
- test/_unit/nrm/behaviours/check-email-token.spec.js
- test/_unit/verify/behaviours/email-lookup-sender.spec.js
- Fix bug where an additional ampersand being added to the end of the magic link when clicked causes an engine error - [NRM-342](https://collaboration.homeoffice.gov.uk/jira/browse/NRM-342)
-  In the past an `&` was added to the end of the magic link  in the getPersonalisation function in the email-lookup-sender behaviour to resolve a bug where `?hof-cookie-check` was being added to the end of the req.query.token (https://github.com/UKHomeOffice/modern-slavery/commit/8bd6451a3c874ba9326f61d7254ca5a2d06fcfdb)
- Currently, with some clients, due to a second ampersand being generated, an nginx error is triggered when the user clicks the magic link, preventing them from accessing their form.
- removed the `&` from the link in the getPersonalisation function in email-lookup-sender behaviour
- …
> NRM-432: fix magic link ampersand bug

- kube/icasework/icasework-resolver-deployment.yml
- yarn.lock
- update icasework resolver image to version using axios - [HOFF-691](https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-691)
- to resolve vulnerabilities caused by deprecated request package
- update icasework resolver image in drone.yml
tested on branch
- updated yarn.lock
> HOFF-691: update icasework resolver image to version using axios

- Dockerfile-acceptance
- acceptance-test/bootstrap/browser.js
- apps/nrm/behaviours/are-you-sure.js
- apps/nrm/behaviours/continue-report.js
- apps/nrm/behaviours/delete-form-session.js
- apps/nrm/behaviours/resume-form-session.js
- apps/nrm/behaviours/save-form-session.js
- apps/nrm/index.js
- browsers/chrome/Dockerfile
- package.json
- yarn.lock
- Update Modern slavery to use version of hof which replaces request module with axios - [HOFF-659](https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-659)
- The request module in hof is deprecated and has vulnerabilities so has been replaced by axios.
- update hof version to use axios
- remove request module in package.json
-  remove request-promise-native module in package.json
- update yarn.lock
- refactored code in save-form-session, resume-form-session, delete-form-session, are-you-sure and continue-report behaviours to use hof model instead of request
- replace request-promise-native with axios for acceptance tests
- update node image versions to fix vulnerabilities and drone build
- update casework-resolver image to version using axios
here is an [example …
> HOFF-659: update nrm to use axios

- apps/nrm/translations/src/en/pages.json
- apps/nrm/views/exploiters-current-location-details.html
- apps/nrm/views/where-are-exploiters.html
Question not announced by screen reader for exploiters-current-location-details field. See [NRM-331](https://collaboration.homeoffice.gov.uk/jira/browse/NRM-331)
This could be due to the radio button element set up on the HoF framework. To fix this issue, we updated the pv-under-age HTML page and hard coded the elements.
A div element was added to include a tab index which was set to 0. This enabled the tab function to pick up the header.
Voice Over was used as a screen reader to test whether the header is being picked up.
> [NRM 331] Question not announced by screen reader for exploiters-current-location-details field

- apps/feedback/fields/index.js
- apps/nrm/fields/index.js
- package.json
- yarn.lock
Update NRM to Preserve Paragraph/Spacing in textures - [NRM-365](https://collaboration.homeoffice.gov.uk/jira/browse/NRM-365)
- add formatting to all textarea fields to preserve paragraphs and spacing
- update hof version and yarn.lock to fix security vulns
tests passing locally, manual testing
Paragraphs and spacing preserved on submission to icasework
> NRM-365: Update NRM to Preserve Paragraph/Spacing

- kube/file-vault/file-vault-deployment.yml
- kube/file-vault/file-vault-ingress.yml
- kube/file-vault/file-vault-network-policy.yml
- kube/file-vault/file-vault-service.yml
Remove branch conditional on filevault ingress and service names so that all branches use the same host and prevent this error:  `for: "STDIN": admission webhook "validate.nginx-external.ingress.kubernetes.io" denied the request: host "fv-ms.ms-branch.homeoffice.gov.uk" and path "/" is already defined in ingress ms-branch/file-vault-ingress-...`
icasework doesn't allow dynamic url hostnames i.e. names changing depending on the branch name they have been given,  so only one filevault host name can be used for all branches.
Changing to a set filevault hostname resulted in the error:  `for: "STDIN": admission webhook "validate.nginx-external.ingress.kubernetes.io" denied the request: host "fv-ms.ms-branch.homeoffice.gov.uk" and path "/" is already defined in ingress …
> HOTFIX: Allow filevault host on all branches

- apps/nrm/fields/index.js
- apps/nrm/translations/src/en/fields.json
- apps/nrm/translations/src/en/pages.json
Amend content for the potential victim location page
As part of a business change request.
* Update radio button content translation for current-pv-location-uk-city in fields.json
* Update radio button content translation for current-pv-location-uk-region in fields.json
* Update current-pv-location header translation in page.json
> NRM-390: Amend content for the pv location page

- apps/nrm/fields/index.js
- apps/nrm/translations/src/en/fields.json
- apps/nrm/translations/src/en/pages.json
- apps/nrm/translations/src/en/validation.json
- test/_ui-integration/nrm/validations.spec.js
NRM-388: Amend content on /why-report-now page - [NRM-388](https://collaboration.homeoffice.gov.uk/jira/browse/NRM-388)
- amend header content
- add intro content
- make label visually hidden
- amend check your answers label
- amend validation message to fit amended content
> NRM-388: Amend content on /why-report-now page

- kube/dashboard/dashboard-deployment.yml
- kube/save-return-lookup/deployment.yml
[NRM-375](https://collaboration.homeoffice.gov.uk/jira/browse/NRM-375) - Deployment to point to Keycloak PROD URL
[NRM-374](https://collaboration.homeoffice.gov.uk/jira/browse/NRM-374) -  Add OAUTH account into prod Keycloak realm 
Discovery url has to be set to keycloak prod
Oath has to be set to point to prod
- Adding a control flow statement to ensure that anything that is in the prod env is pointing at the right realm
- Hard coded values where only pointing to notprod
Prod mirrors non prod so when this is deployed it should work as expected - We could whitelist an IP on prod to ensure there is not discrepancy
> NRM-375: Update keycloak urls for prod

- apps/nrm/fields/index.js
- apps/nrm/translations/src/en/fields.json
- apps/nrm/translations/src/en/pages.json
- apps/nrm/views/where-exploitation-happened-overseas.html
- apps/nrm/views/where-exploitation-happened-uk.html
- assets/js/index.js
Removed number of locations remaining from "Add another" button
Max number of buttons logic to stay the same
Updates to content
for [NRM-396](https://collaboration.homeoffice.gov.uk/jira/browse/NRM-396) & [NRM-398](https://collaboration.homeoffice.gov.uk/jira/browse/NRM-398)
Requested by business
Updates to translations json files & page html files.
Updates to fields/index.js to add bold to font.
Removal of "(X remaining)" from the "Add another" button.
Logic for maximum number of locations (max 10) to remain the same, so not touched the other logic.
NRM-396:
NRM-398:
Branch url: [https://ms-nrm-396-nrm-398-where-expl-happened.internal.ms-branch.homeoffice.gov.uk/start](https://ms-nrm-396-nrm-398-where-expl-happened.internal.ms-branch.homeoffice.gov.uk/start)
here is an [example …
> NRM-396, NRM-398: Content updates: Where exploitation happened

- apps/nrm/fields/index.js
- apps/nrm/index.js
- apps/nrm/models/submission.js
- apps/nrm/sections/summary-data-sections.js
- apps/nrm/translations/src/en/fields.json
- apps/nrm/translations/src/en/pages.json
- apps/nrm/translations/src/en/validation.json
- test/_ui-integration/nrm/application.spec.js
- test/_ui-integration/nrm/automatic-referral-application.spec.js
- test/_ui-integration/nrm/validations.spec.js
Amend content and routing for the "Has the potential victim reported this before page"
As part of a business change request
* Added new child textbox components "not-sure-the-first-chance-to-report" and "yes-the-first-chance-to-report" in fields/index.js so that more detail can be provided as well as amend content for the "is-the-first-chance-to-report" field
* Added new translations for these fields in translations/en/validation.json
* Updated validations unit test to cover cases where new fields exceed 15k characters
* Add new application and automatic referral tests to cover yes and not-sure routing
* Add new API mapping in submission.js
* Add translations for the new fields in translations/en/fields.json as well as amend translation for the "is-the-first-chance-to-report" field 
here …
> NRM-393: Amend content for first chance to report page

- apps/nrm/translations/src/en/fields.json
- apps/nrm/translations/src/en/pages.json
- yarn.lock
NRM-428: Content fixes for /how-why-did-they-leave-the-situation and /how-they-were-treated - [NRM-428](https://collaboration.homeoffice.gov.uk/jira/browse/NRM-428)
- Header for /how-they-were-treated did not match design
- Hint for /how-why-did-they-leave-the-situation  should no longer be on page (was reintroduced when rebasing)
Updated content fields.json and pages.json
tests passing locally
- The label for how-why-did-they-leave-the-situation  is visually hidden, but I have updated the wording so it can be read by screen readers correctly.
- update yarn.lock
> NRM-428: Content fixes for /how-why-did-they-leave-the-situation and /how-they-were-treated

- apps/nrm/behaviours/casework-submission.js
Bug fix : The "Save and exit" option is submitting the form but this should not be happening. 
After investigation detected when `save and exit ` button was clicked the `caseworker-submission` behaviour was also triggered and this latter was submitting the form.
as per business request on Jira ticket [NRM-446](https://collaboration.homeoffice.gov.uk/jira/browse/NRM-446)
Solution: I added a conditional statement to `casework-submission.js` behaviour, so when `save and exit` is clicked it will redirect the user to the `save and exit page` instead of executing the code.
- update casework-submission.js 
manual on local and on branch
> NRM-446 bugfix save-exit button

- apps/nrm/translations/src/en/validation.json
- test/_ui-integration/nrm/validations.spec.js
Bug fix Correct validation typo for 'what-were-they-required-to-do' field
As reporter in [NRM-437](https://collaboration.homeoffice.gov.uk/jira/browse/NRM-437) there was a grammar error in the validation sentence for this field.
- update validation content for `what-were-they-required-to-do` field in `validation.json`
n/a
> NRM-437 [bug-fix] content correction

- apps/nrm/behaviours/casework-submission.js
- apps/nrm/index.js
as per jira ticket [NRM-446](https://collaboration.homeoffice.gov.uk/jira/browse/NRM-446) the Save and exit on /confirm page is submitting report 
quick fix was decided to remove the button form this page
- update index.js /confirm step, removed showSaveAndExit button from screen
> NRM-446 remove save-exit button

- apps/nrm/models/file-upload.js
- test/_unit/nrm/models/file-upload.spec.js
Raised in separate ticket: [NRM-458](https://collaboration.homeoffice.gov.uk/jira/browse/NRM-458)
Fix error associated with [NRM-457](https://collaboration.homeoffice.gov.uk/jira/browse/NRM-457)
* When an error occurs during Model request() call it is returned instead of thrown
* This means we need to explicitly handle the error in a callback
* Otherwise the app will behave as if the upload was successful, but then crashes on submit 
- [] I have written tests (if relevant)
> NRM-458 Fix error missed on file upload

- apps/nrm/translations/src/en/save-and-exit.json
- apps/verify/behaviours/email-lookup-sender.js
[NRM-463](https://collaboration.homeoffice.gov.uk/jira/browse/NRM-463) - Incorrect page title
Expected outcome: The page title was suppose to be - Your report has been saved – Report modern slavery – GOV.UK
Actual outcome: save-and-exit.title – Report modern slavery – GOV.UK
save-and-exit.json file is updated with title property
Local and branch testing
> NRM-463 fix save and exit page title
