README.md, package.json
* How to install and start the app
* Add a node environment variable of development
=> Readme: Install & start app

.drone.yml
Note: You cannot have the secret in the same line
=> Amend drone pipeline

.drone.yml
So these can be used for kube deployment in CI
=> Drone: add drone trigger events & pass variables

.drone.yml
- also delete experimental pipeline steps
=> Drone: image to quay & build app only on master

README.md, apps/nrm/views/content/start.md
* skip email verify instructions
* add start heading to nrm form
=> Readme update: skip verify

README.md, hof.settings.json
It makes it easier to run other hof apps while running this one
=> Change the port to 8081

package.json
So it's clear what tests are being run when pre-commit starts
=> MS-692 task: add pre-commit test order

README.md, acceptance-test/bootstrap/bootstrap.js, acceptance-test/bootstrap/browser.js, acceptance-test/user-pathways/upload-file/upload-file.test.js, acceptance-test/user-pathways/util/get-container-ip.js, acceptance-test/user-pathways/util/selectors.js, browsers/chrome/Dockerfile, browsers/chrome/entrypoint.sh, docker-compose.yml, package-lock.json, package.json
This Pull request will allow you to run remote acceptance tests using Google Chrome within docker containers.
Tests can only be run in headless mode (the browser runs in the background)
=> MS-690 Remote Headless & Non-Headless Acceptance Testing within Docker

acceptance-test/user-pathways/happy-path/happy-path.test.js, acceptance-test/user-pathways/upload-file/upload-file.test.js, acceptance-test/user-pathways/util/selectors.js, apps/nrm/index.js, apps/nrm/translations/src/en/pages.json, apps/verify/index.js, apps/verify/translations/src/en/pages.json
This will create the template for the happy path within the application along with it's acceptance tests
=> MS-714 Create Skeleton of the happy path within application

acceptance-test/user-pathways/happy-path/happy-path.test.js, acceptance-test/user-pathways/upload-file/upload-file.test.js, acceptance-test/user-pathways/util/selectors.js, apps/nrm/fields/index.js, apps/nrm/index.js, apps/nrm/translations/src/en/fields.json, apps/nrm/translations/src/en/pages.json, apps/nrm/translations/src/en/validation.json
Where are you making this report? Page created + acceptance test updated.
=> MS-719 Where are you making this report? Page

Dockerfile
WKHTML is the tool we use to generate PDFs
=> MS-755 - Docker - install wkhtml command tool

Dockerfile, package.json
* add the postinstall script to dockerfile
* move out the delete of the public folder and put it into postinstall
=> MS-755 - Docker - postinstall

apps/verify/translations/src/en/validation.json
Add validation message to organisation field
Regarding Who do you work for? Page
=> MS-718 task: update validation.json

README.md
* Remove a space
* This is to test our automated feature for deploying straight to dev after a merge to master
=> MS-785 - Remove space - test automate deploy to dev

acceptance-test/user-pathways/happy-path/happy-path.test.js, acceptance-test/user-pathways/upload-file/upload-file.test.js, acceptance-test/user-pathways/util/selectors.js, apps/nrm/fields/index.js, apps/nrm/index.js, apps/nrm/translations/src/en/fields.json, apps/nrm/translations/src/en/pages.json, apps/nrm/translations/src/en/validation.json
'select' is keyword that is is retricted by NAXSI
See https://github.com/nbs-system/naxsi/blob/master/naxsi_config/naxsi_core.rules
The 'select' keyword is listed as a risk for SQL injection
Updated the URI to 'fr' to indicate first responder.
=> MS-773 fix: remove 'select' from page URI

acceptance-test/user-pathways/happy-path/happy-path.test.js, acceptance-test/user-pathways/upload-file/upload-file.test.js, acceptance-test/user-pathways/util/selectors.js, apps/modern-slavery/translations/src/en/journey.json, apps/nrm/fields/index.js, apps/nrm/index.js, apps/nrm/translations/src/en/fields.json, apps/nrm/translations/src/en/journey.json, apps/nrm/translations/src/en/pages.json, apps/nrm/translations/src/en/validation.json, apps/verify/translations/src/en/journey.json, assets/scss/app.scss
Who exploited them? Page + acceptance tests
=> MS-730 Who exploited them? Page

acceptance-test/user-pathways/happy-path/happy-path.test.js, acceptance-test/user-pathways/upload-file/upload-file.test.js, acceptance-test/user-pathways/util/selectors.js, apps/nrm/fields/index.js, apps/nrm/index.js, apps/nrm/translations/src/en/fields.json, apps/nrm/translations/src/en/pages.json, apps/nrm/translations/src/en/validation.json, apps/nrm/views/partials/reported-to-police-yes.html, apps/nrm/views/reported-to-police.html, package-lock.json, package.json
Do they have a crime reference number? + acceptance tests
=> MS-733 Do they have a crime reference number? Page

package.json
* node inspector is only for debugging it should not be in the master branch
* it should not be in our environments when running the app
* requires another port to run and slows down the app
=> Fix- remove node inspector

apps/pdf/behaviours/generate-send-pdf.js, test/unit/pdf/behaviours/generate-send-pdf.test.js
* Make functions use async & await feature of node 8
* Make tests use async & await feature of node 8
* Make async functions synchronous
* Makes the functions easier to read and write
* Makes it less messy
=> MS-756: PDF saveValues- fix unit tests

acceptance-test/user-pathways/happy-path/happy-path.test.js, acceptance-test/user-pathways/upload-file/upload-file.test.js, acceptance-test/user-pathways/util/selectors.js, apps/nrm/fields/index.js, apps/nrm/index.js, apps/nrm/translations/src/en/fields.json, apps/nrm/translations/src/en/validation.json, apps/nrm/views/content/does-pv-need-support.md, apps/nrm/views/does-pv-need-support.html
Do they need support? Page + acceptance tests
=> MS-735 Do they need support? Page

acceptance-test/user-pathways/happy-path/happy-path.test.js, acceptance-test/user-pathways/upload-file/upload-file.test.js, apps/nrm/fields/index.js, apps/nrm/index.js, apps/nrm/translations/src/en/fields.json, apps/nrm/translations/src/en/pages.json, apps/nrm/translations/src/en/validation.json, apps/nrm/views/pv-dob.html, package-lock.json, package.json
What is their date of birth? Page + acceptance tests
=> MS-739 What is their date of birth? Page

acceptance-test/user-pathways/happy-path/happy-path.test.js, acceptance-test/user-pathways/upload-file/upload-file.test.js, acceptance-test/user-pathways/util/selectors.js, apps/nrm/fields/index.js, apps/nrm/index.js, apps/nrm/translations/src/en/fields.json, apps/nrm/translations/src/en/pages.json, apps/nrm/translations/src/en/validation.json
What is their gender? Page + acceptance tests
=> MS-740 What is their gender? Page

acceptance-test/user-pathways/happy-path/happy-path.test.js, acceptance-test/user-pathways/upload-file/upload-file.test.js, acceptance-test/user-pathways/util/selectors.js, apps/nrm/fields/index.js, apps/nrm/index.js, apps/nrm/translations/src/en/fields.json, apps/nrm/translations/src/en/pages.json, apps/nrm/translations/src/en/validation.json, apps/nrm/views/does-pv-have-children.html, apps/nrm/views/partials/does-pv-have-children-yes-amount.html
Do they have any children? Page + acceptance tests
=> MS-741 Do they have any children? page

acceptance-test/user-pathways/happy-path/happy-path.test.js, acceptance-test/user-pathways/upload-file/upload-file.test.js, acceptance-test/user-pathways/util/selectors.js, apps/nrm/fields/index.js, apps/nrm/index.js, apps/nrm/translations/src/en/fields.json, apps/nrm/translations/src/en/pages.json, apps/nrm/translations/src/en/validation.json, apps/nrm/views/partials/pv-nationality-second.html, apps/nrm/views/pv-nationality.html
What is their nationality? Page + acceptance tests
=> MS-742 What is their nationality? Page

acceptance-test/user-pathways/happy-path/happy-path.test.js, acceptance-test/user-pathways/upload-file/upload-file.test.js, acceptance-test/user-pathways/util/selectors.js, apps/nrm/fields/index.js, apps/nrm/index.js, apps/nrm/translations/src/en/fields.json, apps/nrm/translations/src/en/pages.json, apps/nrm/translations/src/en/validation.json, apps/nrm/views/partials/pv-other-help-with-communication-aid.html, apps/nrm/views/pv-other-help-with-communication.html
Do they need help with communication? Page + acceptance tests
=> MS-744 Do they need help with communication? Page

acceptance-test/user-pathways/happy-path/happy-path.test.js, acceptance-test/user-pathways/upload-file/upload-file.test.js, acceptance-test/user-pathways/util/selectors.js, apps/nrm/fields/index.js, apps/nrm/index.js, apps/nrm/translations/src/en/fields.json, apps/nrm/translations/src/en/pages.json, apps/nrm/translations/src/en/validation.json, apps/nrm/views/partials/pv-contact-details-email-input.html, apps/nrm/views/partials/pv-contact-details-post.html, apps/nrm/views/pv-contact-details.html
How should we notify them of our decision? Page + acceptance tests
=> MS-746 How should we notify them of our decision? Page

acceptance-test/user-pathways/happy-path/happy-path.test.js, acceptance-test/user-pathways/upload-file/upload-file.test.js, acceptance-test/user-pathways/util/selectors.js, apps/nrm/fields/index.js, apps/nrm/index.js, apps/nrm/translations/src/en/fields.json, apps/nrm/translations/src/en/pages.json, apps/nrm/translations/src/en/validation.json, apps/nrm/views/partials/pv-phone-number-yes.html, apps/nrm/views/pv-phone-number.html
Can the support provider contact them by phone? Page + acceptance tests
=> MS-752 Can the support provider contact them by phone? Page

acceptance-test/user-pathways/happy-path/happy-path.test.js, acceptance-test/user-pathways/upload-file/upload-file.test.js, acceptance-test/user-pathways/util/selectors.js, apps/nrm/fields/index.js, apps/nrm/index.js, apps/nrm/translations/src/en/fields.json, apps/nrm/translations/src/en/pages.json, apps/nrm/translations/src/en/validation.json, apps/nrm/views/content/fr-details.md, apps/nrm/views/fr-details.html
What are your contact details? Page + acceptance tests
=> MS-724 What are your contact details? Page

acceptance-test/user-pathways/happy-path/happy-path.test.js, acceptance-test/user-pathways/upload-file/upload-file.test.js, acceptance-test/user-pathways/util/selectors.js, apps/nrm/fields/index.js, apps/nrm/index.js, apps/nrm/translations/src/en/fields.json, apps/nrm/translations/src/en/pages.json, apps/nrm/translations/src/en/validation.json
Who should we contact in your absence? Page + acceptance tests
=> MS-725 Who should we contact in your absence? Page

README.md
=> ReadMe add full stop

README.md
=> ReadMe- Add colon

apps/nrm/fields/index.js, apps/nrm/translations/src/en/fields.json, apps/nrm/views/any-other-pvs.html, apps/nrm/views/content/any-other-pvs.md
Add required validation for page
Update page content with correct paragraph
=> MS-896 task: add validation to any-other-pvs Page

apps/nrm/behaviours/types-of-exploitation.js, apps/nrm/translations/src/en/validation.json, test/unit/nrm/behaviours/types-of-exploitation.test.js
Update content on Confirm email is right page
=> MS-808 Update Confirm email is right page

acceptance-test/user-pathways/happy-path/happy-path.test.js, apps/nrm/index.js
Allow re-use of nationality page on Duty to notify user journey
=> MS-895 Allow re-use of nationality page on Duty to notify user journey

apps/nrm/index.js, apps/nrm/models/check-your-answers-formatting.js, apps/nrm/translations/src/en/buttons.json, apps/nrm/translations/src/en/pages.json, apps/nrm/views/confirm.html, apps/nrm/views/content/check-your-answers.md, apps/nrm/views/partials/summary-table-potential-victim.html, apps/nrm/views/partials/summary-table-your-details.html, apps/nrm/views/partials/summary-table-your-report.html, apps/nrm/views/partials/summary-table.html, assets/scss/app.scss, package-lock.json, package.json
Check your answers page logic + content
=> MS-676 Check your answers page

apps/nrm/fields/index.js
Required spelling corrected on How many children do you have? Page
=> MS-676 fix: validation typo

apps/nrm/fields/index.js, apps/nrm/index.js, apps/nrm/translations/src/en/pages.json, apps/nrm/views/partials/summary-table-potential-victim.html, apps/nrm/views/partials/summary-table-someone-else.html, apps/nrm/views/partials/summary-table-your-details.html, apps/nrm/views/partials/summary-table-your-report.html, apps/nrm/views/partials/summary-table.html, assets/scss/app.scss, config.js
Add missing pages and data from /confirm page
Add validation for First responder phone number
Add Styling for Alternate contact on /confirm page
Update content in translations regarding /confirm page
=> MS-676 fix: add missing data from /confirm page

package-lock.json, package.json
- required for acceptance tests
=> Fix drone - move chai-shallow-deep-equal to normal dependency

apps/nrm/behaviours/save-missing-data.js, apps/nrm/behaviours/transfer-missing-data.js, apps/nrm/index.js
* For an unknown reason hof deletes some session data
* Workaround to save data temporarily and then transfer them back
=> MS-921 - Fix - missing session data

apps/nrm/behaviours/check-email-token.js, apps/nrm/models/check-token.js, apps/nrm/views/pdf.html, apps/verify/behaviours/email-lookup-sender.js, apps/verify/models/save-token.js, test/unit/nrm/behaviours/check-email-token.test.js, test/unit/nrm/models/check-token.test.js
The first time a user enters email & organisation we do not store their email or organisation.  
This resolves that by storing it in redis in relation to their token
=> MS-958 Add email & organisation

apps/nrm/views/partials/summary-table-your-report.html, assets/scss/app.scss
Fixed Check your answer page - Missing Data (How were they exploited)
=> MS-932 fix: update summary-table-your-report.html

apps/nrm/views/partials/summary-table-potential-victim.html
Fixed PV Nickname incorrectly displayed on check your answer page
=> MS-923 fix: update summary-table-potential-victim.html

apps/nrm/translations/src/en/pages.json, apps/nrm/views/content/fr-details.md, apps/nrm/views/partials/summary-table-your-details.html
Add these additional fields to page content.
=> MS-958 task: add user email and organisation

apps/nrm/translations/src/en/validation.json
Add validation messgage to page
=> MS-935 fix: update validation.json

apps/nrm/views/partials/summary-table-potential-victim.html, apps/nrm/views/partials/summary-table-someone-else.html, apps/nrm/views/partials/summary-table-your-details.html, apps/nrm/views/partials/summary-table-your-report.html
Temporarily remove change buttons on check your answers page.
=> jr-MS-summary-page fix: temporarily remove change buttons

acceptance-test/user-pathways/happy-path/happy-path.test.js, apps/nrm/behaviours/data-to-pdf.js, apps/nrm/behaviours/generate-send-pdf.js, apps/nrm/fields/index.js, apps/nrm/index.js, apps/nrm/translations/src/en/fields.json, apps/nrm/util/transform-data.js, apps/nrm/views/pdf.html, config.js
* reuse transform data for both viewing and also generating the pdf
* update pdf template
* add missing data for gender, extra when going to the confirm page through different routes
=> Ms 971 update pdf & fix missing data

apps/nrm/index.js, apps/nrm/util/transform-data.js, apps/nrm/views/pdf.html
* Update pdf
* Fix bug: pv-phone-number doesn't get saved.  HOF for someone reason deletes it
=> Ms 971-pdf update & fix pv phone number bug

apps/nrm/views/partials/summary-table-your-report.html
Add missing exploitation in summary page
=> MS-932 fix: add missing exploitation

apps/nrm/behaviours/hide-and-show-summary-fields.js, apps/nrm/index.js, apps/nrm/translations/src/en/pages.json, apps/nrm/views/partials/summary-table-potential-victim.html, apps/nrm/views/partials/summary-table-someone-else.html, apps/nrm/views/partials/summary-table-your-details.html
Add logic to ensure correct fields are shown on summary page
Dependant on user's journey through form
=> MS-921 fix: update summary page fields shown

apps/nrm/behaviours/back-links/get-page-back-link.js
Local Authority Page back link needed to be added to new backlink function
=> MS-960 task: add local authority backlink

apps/nrm/translations/src/en/pages.json, apps/nrm/views/partials/summary-table-potential-victim.html, apps/nrm/views/partials/summary-table-someone-else.html, apps/nrm/views/partials/summary-table-your-report.html
Added missing answers and changed the representation of others.
=> MS-921 fix: add missing answers on summary page

apps/verify/behaviours/email-lookup-sender.js, ms-email-domains.js, package-lock.json, package.json
- Use npm ms-email-domains
- allow ithc email domain temporarily for testing
- remove the file with the ms-email-domains
=> MS-988 Update email domains

assets/js/index.js
This is in place to prevent duplicate form submissions.
=> MS-996 task: disable button on form submission

apps/nrm/translations/src/en/pages.json, apps/nrm/views/confirmation.html
=> MS-677 task: add page content

apps/nrm/behaviours/reset-on-change.js, apps/nrm/index.js, package-lock.json, test/unit/nrm/behaviours/reset-on-change.test.js
* Add a behaviour that resets all values except the fields you tell it not to
* Behaviour also saves the steps for back button
* Add unit tests
=> MS-995 Under-18 Reset on change behaviour

package-lock.json, package.json
Update Local Authorities data list
=> MS-947 Update Local Authorities data list

apps/verify/translations/src/en/validation.json
update correct validation error message
=> MS-916 task: update correct validation error message

apps/nrm/translations/src/en/validation.json
Correct the spelling of address
=> MS-918 fix: update validation.json

package-lock.json, package.json
Adds additional email domains.
=> MS-570 task: update package.json ms-email-domains

assets/js/index.js
Breaks typeaheads in IE browsers if no condition is added.
=> MS-996 task: add condition for duplicate submission script

assets/js/index.js
Remove fat arrow functions on index.js
IE browsers break when this is used
=> MS-996 fix: remove fat arrow function

Dockerfile, acceptance-test/bootstrap/browser.js, acceptance-test/user-pathways/happy-path/happy-path.test.js, run.sh
Update Node image to latest version.
Now using alpine image and installing Node + puppeteer dependencies
Updated user access to folders using alpine comands
bash not installed so we have used sh instead
=> MS-1016 task: update nodeJS image

assets/js/index.js
Removed root cause of the issue
=> application skipping pages with confirm in the URL

apps/verify/index.js, apps/verify/translations/src/en/pages.json, apps/verify/views/paper-version-download.html, apps/verify/views/start.html, assets/js/index.js
Landing page to download offline form
=> MS-678 task: create offline crib landing page

apps/nrm/util/transform-data.js, apps/nrm/views/pdf.html
* fix typos
* display missing sections
* amend content
=> MS-989 pdf-update

apps/nrm/index.js, test/unit/nrm/behaviours/reset-on-change.test.js
add user email and organisation to stored variable list on reset.
=> MS-995 fix: include missing variables to store on reset.

package-lock.json, package.json
To include missing email domain to be whitelisted
=> MS-570 task: update email domains version

package-lock.json, package.json
update package.json to include the missing region according to spreadsheet
=> MS-947 task: update UK regions

apps/verify/behaviours/email-lookup-sender.js
Update email details with a link to the application host page
=> MS-967 task: add host link to Notify email

apps/nrm/views/content/session-timeout.md, apps/nrm/views/session-timeout.html, apps/verify/views/content/session-timeout.md, apps/verify/views/session-timeout.html
Override session timeout message
=> MS-967 task: override session-timeout message

package-lock.json, package.json
Update package.json with the the update ms-email-domains version
=> MS-1029 task: update ms-email-domains

package-lock.json, package.json
Update package.json for ms-organisations
=> MS-911 task: update FR organisation list

package-lock.json, package.json
=> MS-911 task: revert FR update

package-lock.json, package.json
revert ms-organisations version
=> MS-911 task: revert ms-organisations version

apps/nrm/translations/src/en/pages.json
Update pages.json content for confirmation page
=> MS-1021 task: update confirmation page content

package-lock.json, package.json
=> MS-911 task: update ms-organisations list

apps/feedback/index.js, apps/feedback/translations/src/en/pages.json, apps/feedback/views/complete.html, apps/nrm/views/confirmation.html
=> MS-1064 task: update  feedback link

apps/feedback/util/send-email.js, config.js
=> MS-1064 task: add feedback template

apps/feedback/behaviours/send-feedback.js, apps/feedback/util/data-formatter.js
Feedback data collected from different source
=> MS-1064 task: update feedback data collection

apps/common/translations/src/en/errors.json, apps/common/views/session-timeout.html
=> MS-1061 task: update session message

index.js
=> MS-1104 task: add HTML Language

apps/verify/translations/src/en/fields.json, apps/verify/translations/src/en/validation.json
- Update user instruction and error message.
- To make it clear to the user what to do.
=> MS-1142 fix: update error message.

apps/nrm/translations/src/en/fields.json, apps/verify/translations/src/en/fields.json
https://jira.digital.homeoffice.gov.uk/browse/MS-1149
=> MS-1149 - accessibility - add hint to all typeahead fields

govuk_template.html, index.js
- Override govuk-template to add alt tags to images
=> MS-1103 task: add alt tag to gov images

apps/nrm/translations/src/en/fields.json, apps/nrm/views/partials/pv-nationality-second.html, apps/verify/views/partials/find-organisation.html
- Remove details tags and show the static text.
- Update labels
=> MS-1141 MS-974 task: update detail tags

apps/verify/views/partials/find-organisation.html
Update content on who do you work for page
=> MS-1141 task: update content

apps/nrm/behaviours/generate-send-pdf.js, test/unit/nrm/behaviours/generate-send-pdf.test.js
=> MS-1099 task: update generate-send-pdf.js

apps/nrm/views/confirmation.html, apps/verify/views/partials/find-organisation.html, apps/verify/views/who-do-you-work-for.html
- Update who-do-you-work-for page content to reflect prototype
- Remove redundant full stops from confirmation page & who-do-you-work-for page
=> MS-1141 MS-974 task: update content

apps/verify/behaviours/confirm-email-passer.js, apps/verify/index.js, apps/verify/translations/src/en/pages.json, apps/verify/views/check-inbox.html, apps/verify/views/content/check-inbox.md, test/unit/verify/behaviours/confirm-email-passer.test.js
https://jira.digital.homeoffice.gov.uk/browse/MS-1144
=> MS-1144 verify journey: display email on final page

apps/nrm/translations/src/en/pages.json, apps/nrm/views/content/start.md, apps/verify/translations/src/en/pages.json, apps/verify/views/start.html
- Added Page title to header on start page
- Removed start page breadcumbs
- Added page title to confirmation page
=> MS-1138 MS1105 task: updated page headings

apps/nrm/translations/src/en/fields.json
=> MS-901 task: update field label

apps/nrm/translations/src/en/fields.json
- Update refuse-nrm field label
=> MS-1058 task: update label content

apps/nrm/fields/index.js, apps/nrm/translations/src/en/fields.json, apps/nrm/views/partials/pv-under-age-panel-not-sure.html, apps/nrm/views/partials/pv-under-age-panel-yes.html, apps/nrm/views/partials/pv-under-age-panel.html
- Update not sure field content
=> MS-1056 task: update field content

apps/nrm/translations/src/en/validation.json, apps/verify/translations/src/en/validation.json
- Update validation error messages
=> MS-970 task: update validation messages

apps/common/views/session-timeout.html
- Update link on session timeout page
=> MS-1061 fix: update url link

apps/verify/translations/src/en/pages.json, config.js
- Increase session timeout to 1 hour
- Update all references to the session timeout; reflecting the new limit
=> MS-1098 task: increase session timeout to 1 hour

apps/common/views/layout.html, package-lock.json, package.json
Hof has been updated with some of the latest GDS error design, such as `Error summary appears at the top`, `Page title is prefixed with error at the beginning`
* Update hof-theme-govuk to 4.2 to get this
* Amend layout.html because it overrrides the default one
=> MS-1140 Accessibility - use updated GDS error design

package-lock.json, package.json
- update to gds guidelines
- get new error validation message `There is a problem`
=> MS-1140 bump hof-theme-govuk 4.3.0

apps/nrm/views/content/does-pv-need-support.md, apps/verify/views/start.html
- Accessibility users made aware of links opening in new tabs
=> MS-1139 task: links open in new tab awareness

package-lock.json, package.json
=> MS-1159 task: update ms-email-domain list

apps/common/views/layout.html
- Replace dash in title with accessible friendly dash.
=> MS-1176 task: replace dash

apps/nrm/translations/src/en/fields.json, apps/nrm/views/content/pv-nationality.md
- Remove the apostrophe from 'Unknown' so accessible users are not confused
=> MS-1175 task: remove apostrophe from 'Unknown'

apps/nrm/views/confirmation.html, apps/nrm/views/content/does-pv-need-support.md, apps/verify/views/partials/find-organisation.html, apps/verify/views/start.html
- Remove target="_blank" from links
- GDS advise against this
=> MS-1168 task: remove ability to open links in a new tab

apps/nrm/views/token-invalid.html
- Update Request another token link URL
=> MS-1170 task: update link URL

apps/verify/views/email-not-recognised.html
- Update the URL for the Re-enter your email button
=> MS-1169 task: update link URL

apps/verify/behaviours/email-lookup-sender.js, apps/verify/util/check-email-ext.js, test/unit/verify/util/check-email-ext.js
Can pass in an array of extensions that can be whitelisted 💥
=> MS-1031 Whitelist the email extensions with an array 💥 

package-lock.json, package.json
- ms-email-domains package version updated
=> MS-1209 task: update ms-email-domains package

apps/nrm/fields/index.js, apps/nrm/translations/src/en/fields.json, apps/nrm/views/partials/pv-want-to-submit-nrm-no.html
- Update label on pv-want-to-submit-nrm
- Remove label html files and content
=> MS-1163 task: update label on pv-want-to-submit-nrm

apps/nrm/fields/index.js, apps/nrm/translations/src/en/validation.json, apps/verify/fields/index.js, apps/verify/translations/src/en/validation.json
- Add max character limit to input fields
=> MS-684 task: add max character limit to input fields

README.md, apps/nrm/behaviours/casework-submission.js, apps/nrm/index.js, apps/nrm/models/i-casework.js, apps/nrm/models/submission.js, config.js, docker-compose.yml, package-lock.json, package.json
This maps the data from the nrm form to the iCasework backend.
In order to get this working you will need to export the following env vars:
`ICASEWORK_KEY` and `ICASEWORK_SECRET`
You will also need to ensure that your external IP has been set in the admin interface under the appropriate API key.
=>  Casework submission to iCasework

README.md, package-lock.json, package.json
- Update npm command for coverage reporting
- Update readme regarding coverage reporting
=> MS-1233 task: update npm command for coverage reporting

apps/nrm/util/transform-data.js, apps/nrm/views/pdf.html
- Ensure new fields from where pv was exploited page are added to PDF output
=> MS-1214 task: add new fields to PDF output

apps/nrm/behaviours/generate-send-pdf.js
- Remove API request from console logs when PDF is sent
- Replace with simple message to confirm submission of PDF
- Only output error message if error has occurred
- Remove all other occurences of  data regarding the PDF file
=> MS-1257 task: remove API request from console logs

apps/nrm/views/partials/summary-table-your-report.html
- Add change links to where-exploitation-happened fields
=> MS-940 task: add change links to where-exploitation-happened on CYA Page

apps/nrm/behaviours/back-links/page-custom-back-links.js, apps/nrm/behaviours/next-steps/page-custom-next-steps.js, apps/nrm/index.js
- Reset form values on changing where-exploitation-happened answer
=> MS-1122 task: reset form values on changing page answer

apps/nrm/models/submission.js
- Update uppercase function with valid name
=> MS-1254 task: update function

apps/nrm/behaviours/delete-on-change.js, apps/nrm/index.js
- Add conditonal option to delete fields from session
=> MS-1008 fix: add conditional for deleting fields from session

apps/nrm/index.js
- remove fields that shouldn't be deleted on change
=> MS-1007 fix: remove fields that shouldn't be deleted on change

apps/verify/behaviours/email-lookup-sender.js, package-lock.json, package.json
- Update whitelist module version number
- Add pnn.police.uk to list of email extensions
=> MS-1232 task: add pnn.police.uk to whitelist + update whitelist module

apps/nrm/translations/src/en/fields.json, apps/nrm/translations/src/en/pages.json
- update content on where pv was exploited pages
=> MS-1273 task: update content on where pv was exploited pages

apps/nrm/translations/src/en/fields.json
- remove hint text for optional city
=> MS-1273 task: remove hint text for optional city

apps/verify/translations/src/en/pages.json, apps/verify/views/privacy.html
- Updated privacy page content
=> MS-1193 task: update privacy page to include public beta

package-lock.json, package.json
- update ms-organisations version
=> MS-1232 task: update ms-organisations version

apps/verify/translations/src/en/pages.json
=> MS-1275 task: update privacy page content

package-lock.json, package.json
- update ms-organisations module version number
=> MS-1293 task: update FR list

apps/nrm/behaviours/casework-submission.js, apps/nrm/behaviours/generate-send-pdf.js, config.js, test/unit/nrm/behaviours/generate-send-pdf.test.js
This assists testers in debugging issues with the app and icasework
=> Allow testers to see the json payload on submission

apps/verify/translations/src/en/pages.json, apps/verify/views/privacy.html
- Revert back to private beta content.
=> MS-1193 task: revert private beta to public beta in privacy page

apps/verify/translations/src/en/pages.json
- Update private beta heading on privacy page
=> MS-1193 task: update private beta heading

apps/nrm/translations/src/en/pages.json, apps/nrm/views/confirmation.html
- update referral confirmation page content
=> MS-1261 task: update referral confirmation page content

apps/nrm/behaviours/generate-send-pdf.js, test/unit/nrm/behaviours/generate-send-pdf.test.js
=> MS-1340 add second PDF email to FR's

config.js
Removing the session timeout from the code so that it can be set as an environment variable in k8
=> MS-1361 Remove session timeout

apps/nrm/models/submission.js
There's an issue that we're sending through data for the form that defaults when nothing has been selected.
This addresses those problems and possible side effects on the casework side.
https://jira.digital.homeoffice.gov.uk/browse/MS-1341
=> Don't default all fields with data

apps/nrm/behaviours/check-email-token.js, test/unit/nrm/behaviours/check-email-token.test.js
- Delete user token after use to alleviate token issues being experienced by end-users
=> MS-1373 task: do not delete user token after use.

package-lock.json, package.json
- Update package verison to 1.1.9 to reflect latest changes / additions.
=> MS-1379 task: update ms-email-domains package

apps/nrm/behaviours/check-email-token.js, test/unit/nrm/behaviours/check-email-token.test.js
- ensure token is deleted once it has been used.
- alternative resolution to issue has been preferred.
=> MS-1388 task: revert MS-1373

apps/feedback/behaviours/send-feedback.js, apps/feedback/fields/index.js, apps/feedback/index.js, apps/feedback/translations/src/en/fields.json, apps/feedback/translations/src/en/validation.json, apps/feedback/views/content/start.md, config.js, test/unit/feedback/behaviour/send-feedback.test.js
- add optional email address to feedback form
- add unit test for send-feedback behaviour
- add new template ID in config for new feedback form
=> MS-1385 task: add new email input to feedback form

apps/nrm/behaviours/check-email-token.js, config.js, test/unit/nrm/behaviours/check-email-token.test.js
- Also add a flag for allowing the skip.  This is because HOF needs to be in prod mode to make logs json.  Therefore, we can't rely on the dev environment flag.  However, it's useful to keep this skip for that too incase of local development
=> Ms 1389 delete token on start button

apps/nrm/translations/src/en/pages.json, apps/nrm/views/partials/summary-table-potential-victim.html, package-lock.json
- Update question titles
- Add missing pv-phone-number
=> MS-928 task: update CYA page question titles

apps/nrm/translations/src/en/pages.json, apps/nrm/views/content/local-authority-contacted-about-child.md
- local-authority-contacted-about-child content updated
=> MS-1123 task: update page content in pages.json

apps/nrm/views/partials/summary-table-your-report.html
- add full stops to the end of each exploiation type on CYA page
- help visually impared users understand each sentence in isolation rather than in one long stream
=> jr-MS-1187 task: update CYA page

.drone.yml, documents/release-guidelines.md
- update drone.yml
- incorporate deployments to dev in drone pipeline
=> MS-1387 task: automate deployments to dev

apps/nrm/translations/src/en/fields.json, apps/nrm/translations/src/en/pages.json
- someone-else page heading updated
- pv-contact-details page heading updated
=> MS-1383 task: update page headings

.drone.yml
- correct indentation on drone.yml
- when a task is not run it's usually the indentation
=> MS-1387 fix: update drone.yml

apps/nrm/behaviours/generate-send-pdf.js, package-lock.json, test/unit/nrm/behaviours/generate-send-pdf.test.js
=> MS-1436 task: remove FR PDF notification

README.md, apps/nrm/models/data-service.js, package-lock.json, package.json
- add data-service api to model folder
=> Jr ms 1463 add data service api as a model

apps/nrm/behaviours/get-saved-report.js, apps/nrm/models/read-saved-report-data.js, test/unit/nrm/models/read-saved-report-data.test.js
- add read functionality with app to use data service api
=> MS-1463 add read functionality with data-service api

apps/nrm/behaviours/save-report.js, apps/nrm/views/pv-under-age.html, config.js, package-lock.json, package.json
=> ms 1463 add data service config

apps/verify/behaviours/email-lookup-sender.js, package-lock.json, package.json, test/unit/verify/behaviours/email-lookup-sender.test.js
Some changes to allow modern-slavery to interact correctly with the updated ms-email-domains module
=> Ms 1359 govuk incorrectly behaving as whitelisted address

.drone.yml
- allow save and return to be published to quay in order to test
=> MS-1463 allow all branches to be sent to quay.io

apps/nrm/models/write-saved-report-data.js
- update write function to match api
=> MS-1463 update write function data

apps/nrm/translations/src/en/pages.json, apps/nrm/views/content/save-report.md, apps/nrm/views/save-report.html
- add save report status page content
=> MS-1463 add save report status page

apps/common/data-service.js, apps/nrm/models/read-saved-report-data.js, apps/nrm/models/write-saved-report-data.js, apps/verify/models/cookie.js, apps/verify/models/read-cookie.js, apps/verify/models/write-cookie.js, package-lock.json, test/unit/nrm/models/read-saved-report-data.test.js, test/unit/nrm/models/write-saved-report-data.test.js, test/unit/verify/models/cookie.js
* Write to the db to add a new nrm cookie
* Read a nrm cookie returning the uuid
* Search for a nrm cookie
=> MS 1455 save return cookie

apps/nrm/behaviours/get-saved-report.js
- add read report behaviour to app
=> MS 1463 add read report behaviour

apps/nrm/behaviours/get-saved-report.js, apps/nrm/views/check-your-answers-so-far.html, apps/nrm/views/partials/check-your-answers-so-far-summary-table-potential-victim.html, apps/nrm/views/partials/check-your-answers-so-far-summary-table-someone-else.html, apps/nrm/views/partials/check-your-answers-so-far-summary-table-your-details.html, apps/nrm/views/partials/check-your-answers-so-far-summary-table-your-report.html, apps/nrm/views/partials/check-your-answers-so-far-summary-table.html
- Update Read report behaviour
- add CYA page content
=> MS-1463 check yours answers so far basic

apps/common/behaviours/send-save-report-token.js, apps/common/models/read-token.js, apps/common/models/save-report-tokens.js, apps/common/models/write-token.js, apps/nrm/behaviours/check-save-report-token.js, apps/nrm/fields/index.js, apps/nrm/index.js, apps/nrm/models/write-report-token.js, apps/nrm/translations/src/en/pages.json, apps/verify/fields/index.js, apps/verify/index.js, apps/verify/models/cookie.js, apps/verify/translations/src/en/fields.json, apps/verify/translations/src/en/pages.json
* GET request based on UUID
* POST request providing created date, UUID & useremail
=> MS-1592 create save token link API requests

apps/verify/behaviours/email-lookup-sender.js, package-lock.json, package.json, test/unit/verify/behaviours/email-lookup-sender.test.js
- revert whitelisting changes made on PR #372
- Issues with fix: When entering an email id that is not whitelisted and then reconfirming the email the user is then displayed with Page not found page, which is not expected.
=> MS-1359 revert whitlisting changes

apps/verify/behaviours/email-lookup-sender.js, package-lock.json, package.json, test/unit/verify/behaviours/email-lookup-sender.test.js
Reverts UKHomeOffice/modern-slavery#393
url change required so we will roll back and keep the original fix
=> Revert "MS-1359 revert whitlisting changes"

package-lock.json, package.json
- update ms-organisations package to latest version
=> MS-1597 update ms-organisations version

apps/nrm/translations/src/en/fields.json, apps/nrm/views/pv-want-to-submit-nrm.html, test/unit/verify/behaviours/confirm-email-passer.test.js, test/unit/verify/behaviours/email-lookup-sender.test.js
- Altered text on /nrm/pv-want-to-submit-nrm page.
- Changes to fix two failing tests.
=> SD-92 Update Text Content

package.json
Jira Ticket: https://collaboration.homeoffice.gov.uk/jira/browse/SD-94
Updated ms-uk-local-authorities version to 2.2.2
=> SD-94: updated ms-uk-local-authorities to 2.2.2

apps/nrm/translations/src/en/fields.json
**Jira Ticket**: https://collaboration.homeoffice.gov.uk/jira/browse/SD-298
**Changes**
* Changed word "use" with "process" on the  pv-want-to-submit-nrm page.
* Wording Changed after the "Yes" option on the same page, to include "along with the Privacy Information Notice".
=> SD-298: Amendment to text on pv-want-to-submit-nrm page.

.gitignore, apps/common/translations/src/en/cookies.json, index.js
- The cookie was incorrectly displaying as hmbrp.sid instead of modern-slavery.hof.sid in /cookies
- create new cookies translations file to overwrite default content on the cookies page
=> SD-514 fix incorrect session cookie on cookies page

apps/common/translations/src/en/pages.json, apps/common/views/start.html
Adds new link to 'First Responder guidance' list on the '/start' page
Ticket https://collaboration.homeoffice.gov.uk/jira/browse/SD-476
Changes to HTML template and added translations
=> SD-476: Add new link to first responder list

package-lock.json, package.json
-to show seen_cookie_message in cookie policy whether ga_tag is set or unset
=> SD-709 update to hof-template partials

.drone.yml
=> reverting mistake

README.md
=> edited readme to build kube-moden-slavery

apps/nrm/translations/src/en/pages.json
Changed the SCA number on the confirmation page. 
https://collaboration.homeoffice.gov.uk/jira/browse/SD-840
Business Request 
String change
=> SD-840 SCA Phone number change

.drone.yml
**Changes**
-  drone.yaml changed to include DATA_SERVICE_VERSION, ALERT_SERVICE_VERSION and LOOKUP_SERVICE_VERSION for all deployment environments. Will help deploy all these services from this main modern slavery pipeline.
=> SD-835: Drone file changed to include environment variables for the data, alert and lookup service.

package-lock.json, package.json
**Changed**
* Updated  package.json to include HOF version 18.2.4
=> SD-976: HOF Update to 18.2.4

.drone.yml
**Changes**
- Updated .drone.yml file to include new DATA_SERVICE_VERSION, ALERT_SERVICE_VERSION, and LOOKUP_SERVICE_VERSION, to fix errors within these two environments.
=> SD-1017: Updated pipeline to bring in new Data, Alert, and Lookup Service version for Dev and Preprod.

.drone.yml
**Changes**
- Changed drone.yml versions under deploy_to_preprod
=> SD-1017: Changed Data, Alert and Lookup Service versions for preprod to match current running production versions

.drone.yml
Add missing gitlab username and tokens
Because the current ones have been deleted
=> fix pipeline by adding gitlab username and tokens

apps/common/index.js, apps/common/translations/src/en/pages.json, apps/common/views/paper-version-download.html, package.json, yarn.lock
* If you go directly to the prompt sheet page, it gives you a 401 error, this is regarding the session
* The issue is that this is working like a form if you go to this page.  It shouldn't be.  This isn't a form so make it work more like a web page.
Note: it's still not great as we shouldn't have any form aspects to it but this will do for now
Locally and it works now
=> NRM-93 fix broken prompt sheet link

apps/nrm/translations/src/en/fields.json, apps/nrm/translations/src/en/pages.json, package-lock.json
Change the text for some of the questions.
For improved clarity - some First Responders are confused about whose name is being referred to in some the questions
Amended the text in the questions
Tested locally
=> NRM-90: change some question text

.snyk, package.json, yarn.lock
**Changes**	
- Upgraded HOF to 19.11.23
- Added exception into snyk file for request
=> NRM-96: HOF update and Snyk scan vulnerability

package-lock.json, package.json, yarn.lock
Bump ms-email-domains package to 2.4.0
To add domain to whitelist
added domain to whitelist in ms-email-domains package and updated package in modern slavery
Tested locally
=> Nrm 45 bump ms email domains

apps/nrm/behaviours/are-you-sure.js, apps/nrm/behaviours/delete-form-session.js, apps/nrm/behaviours/resume-form-session.js, kube/save-return-data-alerts/deployment.yml, kube/save-return-lookup/deployment.yml
=> Nrm 102 504 issue

apps/nrm/behaviours/are-you-sure.js, apps/nrm/behaviours/check-email-token.js, apps/nrm/behaviours/continue-report.js, apps/nrm/behaviours/resume-form-session.js, apps/nrm/behaviours/save-form-session.js, apps/nrm/behaviours/types-of-exploitation.js, apps/nrm/fields/index.js, apps/nrm/index.js, apps/nrm/translations/src/en/fields.json, apps/nrm/translations/src/en/validation.json, apps/nrm/views/are-you-sure.html, apps/nrm/views/partials/summary-table-your-report.html, apps/nrm/views/reports.html, apps/verify/behaviours/email-lookup-sender.js, test/_unit/nrm/behaviours/types-of-exploitation.spec.js
=> NRM-79: Reveal exploits section on the check your answers page

kube/icasework/icasework-resolver-deployment.yml
NRM-28 use the latest icw resolver with timestamps
=> NRM-28 use the latest icw resolver with timestamps

kube/icasework/icasework-resolver-deployment.yml, package.json
update icw resolver image with verbose logging
This is to diagnose the duplication issue
=> NRM-120 icw resolver update with verbose logging

package.json, yarn.lock
update ms-email-domains and ms-organisations packages
To incorporate adding domain names to whitelist and organisations to first responder list
=> nrm-134: update ms-email-domains and ms-organisations packages

README.md, package.json, yarn.lock
Updated readme to include instructions on how developers can set up the save and return feature on their local computers. 
Update the documentation for the service
=> Updated README with save and return section

apps/nrm/translations/src/en/fields.json, apps/nrm/translations/src/en/pages.json
Update for NRM-140 update for content
=> NRM-140 updated reported-to-police page header content

README.md
create new branch environment for merging into master and testing GA4 in UAT env
https://collaboration.homeoffice.gov.uk/jira/browse/NRM-144
=> NRM-144: test GA4 migration

package.json, test/setup.js, yarn.lock
- Hotfix: fix failing drone tests - [NRM-314](https://collaboration.homeoffice.gov.uk/jira/browse/NRM-314)
- test envs were not being picked up on drone causing tests to fail when merged to master
- added test envs for AWS_SQS and DELETION_TIMEOUT to test/setup.js
- extend test timeout
- update yarn.lock
- test passing locally and in drone
=> NRM-314: fix failing drone tests

.drone.yml
Ensuring tests are running on the branch environment
As requested by product owner per ticket [NRM 302](https://collaboration.homeoffice.gov.uk/jira/browse/NRM-302)
Fixed indentation on the drone.yml file
unit test and integration test pass
=> [NRM 302] Ensuring tests on branch environment

apps/common/views/accessibility.html
updated accessibility statement 
as per product owner request on [NRM-271](https://collaboration.homeoffice.gov.uk/jira/browse/NRM-271) ticket
updated relevant file 
Sanity testing
=> [NRM-271] updated accessibility statement

README.md, apps/common/behaviours/custom-dialog-text.js, apps/common/index.js, apps/common/translations/src/en/exit.json, apps/common/translations/src/en/pages.json, apps/common/views/accessibility.html, apps/common/views/designated-organisations.html, apps/common/views/exit.html, apps/common/views/paper-version-download.html, apps/common/views/privacy.html, apps/common/views/start.html, apps/common/views/support-organisations.html, apps/nrm/index.js, apps/nrm/translations/src/en/save-and-exit.json, apps/nrm/views/save-and-exit.html, apps/verify/index.js, apps/verify/views/privacy.html, apps/verify/views/session-timeout.html, hof.settings.json, package.json, test/_unit/common/custom-dialog-text.spec.js, yarn.lock
- NRM-358: Update NRM to HOF version with Session Timeout Warning - [NRM-358](https://collaboration.homeoffice.gov.uk/jira/browse/NRM-358)
- To comply with WCAG 2.2 accessibility requirements
- update hof version in package.json and update yarn.lock
- amend static pages(start, accessibility, paper-version-download, privacy, support-organisations, designated-organisations and session-timeout, token-invalid, save-and-exit  views) to not show warning message,
- add /session-timeout and /exit steps to common/index.js,  add /exit steps to nrm/index and verify/index
- add missing showSaveAndExit locals to /confirm step in nrm/index and remove unnecessary commented code in nrm/index.js
- customise exit and save-and-exit pages to use existing NRM content
- add behaviour to customise one line of …
=> NRM-358: Update NRM to latest version of hof to implement session timeout warning

bin/deploy.sh, kube/app/deployment.yml, kube/file-vault/file-vault-deployment.yml, kube/file-vault/file-vault-ingress.yml, kube/file-vault/file-vault-network-policy.yml, kube/file-vault/file-vault-service.yml, kube/save-return-lookup/deployment.yml
- NRM 361 - setup file-vault and keycloak config
[NRM-361](https://collaboration.homeoffice.gov.uk/jira/browse/NRM-361) 
[NRM-362](https://collaboration.homeoffice.gov.uk/jira/browse/NRM-362)
[NRM-363](https://collaboration.homeoffice.gov.uk/jira/browse/NRM-363)
- Adding new file-vault config files 
- To enable file uploads
- created filevault config files, added relevant envs to app/deployment, added filevault deployment scripts, added config relevant to point to the new prod keycloak realm.
- Manual 
=> NRM 361 - configure keycloak and file-vault config

apps/nrm/translations/src/en/fields.json, apps/nrm/translations/src/en/pages.json, apps/nrm/views/content/refuse-nrm.md
NRM-383: Amend content on refuse-nrm page - [NRM-383](https://collaboration.homeoffice.gov.uk/jira/browse/NRM-383)
- per business request
- Amend content in label, header and intro text
tests passing locally and on branch
=> NRM-383: Amend content on refuse-nrm page

apps/nrm/fields/index.js, apps/nrm/translations/src/en/fields.json, apps/nrm/translations/src/en/pages.json, apps/nrm/views/were-they-taken-somewhere-by-their-exploiter.html
…iter
Update content for were-they-taken-somewhere-by-their-exploiter page
Business change requested
- Update text for translations
- Create html file for page so that layout can be adjusted to match the new designs
=> NRM-385: Update content for taken-somewhere-page

apps/nrm/fields/index.js, apps/nrm/index.js, apps/nrm/models/submission.js, apps/nrm/sections/summary-data-sections.js, apps/nrm/translations/src/en/fields.json, apps/nrm/translations/src/en/pages.json, apps/nrm/translations/src/en/validation.json, apps/nrm/views/content/any-other-pvs.md, test/_ui-integration/nrm/validations.spec.js
Amend content and add new field for /any-other-pvs - [NRM-412](https://collaboration.homeoffice.gov.uk/jira/browse/NRM-412)
- amend intro content
- add and configure fields
- add validations
- add fields to summary page
- add submission field for icasework
- amend submission for OtherVictims so that answers appear in plain wording when in icasework
- add ui tests
tests passing locally
=> NRM-412: Amend content and add new field for /any-other-pvs

.drone.yml
NRM-417: Create asynchronous drone build - [NRM-417](https://collaboration.homeoffice.gov.uk/jira/browse/NRM-417)
- allow for quicker drone builds
- amend steps in drone.yml
=> NRM-417: Make drone pipeline asynchronous

apps/nrm/fields/index.js, apps/nrm/index.js, apps/nrm/models/submission.js, apps/nrm/sections/summary-data-sections.js, apps/nrm/translations/src/en/fields.json, apps/nrm/translations/src/en/pages.json, apps/nrm/translations/src/en/validation.json, apps/nrm/views/content/how-did-they-leave-the-situation.md, apps/nrm/views/how-did-they-leave-the-situation.html, apps/nrm/views/what-is-keeping-them-in-situation.html, test/_ui-integration/nrm/application.spec.js, test/_ui-integration/nrm/automatic-referral-application.spec.js, test/_ui-integration/nrm/validations.spec.js, test/helpers/supertest_session/session-data/nrm/steps.js
NRM-401: Create a 'Is the potential victim still in an exploitative situation?' page - /is-the-potential-victim-still-in-an-exploitative-situation - [NRM-401](https://collaboration.homeoffice.gov.uk/jira/browse/NRM-401)
NRM-406: Create a 'What is keeping the potential victim in the situation?' page - /preventing-potential-victim-from-leaving - [NRM-406](https://collaboration.homeoffice.gov.uk/jira/browse/NRM-406)
NRM-410: Amend content for /how-why-did-they-leave-the-situation - [NRM-410](https://collaboration.homeoffice.gov.uk/jira/browse/NRM-410)
NRM-401: Create a 'Is the potential victim still in an exploitative situation?' page
- add page and amend routing
- configure field
- add validations
- add field to summary page
- add submission field for icasework
- add …
=> NRM-401, NRM-406 and NRM-410: Amend exploitative situation pages

apps/nrm/behaviours/multiple-exploitations.js, apps/nrm/fields/index.js, apps/nrm/index.js, apps/nrm/models/submission.js, apps/nrm/sections/summary-data-sections.js, apps/nrm/translations/src/en/fields.json, apps/nrm/translations/src/en/pages.json, apps/nrm/translations/src/en/validation.json, apps/nrm/views/content/how-did-the-exploitation-start.md, apps/nrm/views/content/who-exploited-pv.md, apps/nrm/views/how-did-the-exploitation-start.html, apps/nrm/views/how-they-were-treated.html, apps/nrm/views/who-exploited-pv.html, test/_ui-integration/nrm/application.spec.js, test/_ui-integration/nrm/automatic-referral-application.spec.js, test/_ui-integration/nrm/validations.spec.js, yarn.lock
NRM-403: Amend content and add conditional text for /how-did-the-exploitation-start - [NRM-403](https://collaboration.homeoffice.gov.uk/jira/browse/NRM-403)
NRM-404: Amend content, routing and add conditional text for /how-they-were-treated - [NRM-404](https://collaboration.homeoffice.gov.uk/jira/browse/NRM-404)
NRM-405: Amend content and add conditional text for /who-exploited-pv - [NRM-405](https://collaboration.homeoffice.gov.uk/jira/browse/NRM-405)
NRM-403: Amend content and add conditional text for /how-did-the-exploitation-start
- amend content
- add conditional text and logic
NRM-404: Amend content, routing and add conditional text for /how-they-were-treated
- amend content and amend routing
- configure new field and move field no longer in use to bottom of …
=> NRM-403, NRM-404, NRM-405: Amend content and routing, and add conditional text

README.md
Error on the webhook causing Drone pipeline not to build when merging to master
Drone pipeline not building when merging to master and getting the ff error in the webhook delivery tab:
`tls: failed to verify certificate: x509: certificate is valid for ingress.local, not [drone-external.acp.homeoffice.gov.uk](http://drone-external.acp.homeoffice.gov.uk/).`
I changed the webhook
Merge to see if it runs
@Rhodine-orleans-lindsay will delete the comment on her next PR
=> NRM-WHOOK - testing the webhook

apps/nrm/translations/src/en/pages.json
Fix typo on pv-want-to-submit-nrm page
'referred' was spelt incorrectly
-  amended content in pages.json
=> HOTFIX: Fix typo on pv-want-to-submit-nrm page

apps/nrm/views/content/when-did-the-exploitation-take-place-multiple.md
Fix typo on when-did-exploitation-take-place-multiple page
To correct incorrect spelling
- amend content in when-did-exploitation-take-place-multiple.md
tests passing locally
=> HOTFIX: Fix typo on when-did-exploitation-take-place-multiple page

kube/dashboard/dashboard-deployment.yml
Ahead of the release - [NRM-441](https://collaboration.homeoffice.gov.uk/jira/browse/NRM-441)
We need to ensure the Keycloak realm is configured correctly
By making sure all the config is set correctly
=> NRM-441 correction to the realm name on prod

apps/nrm/views/content/who-contact.md
content update 
as per Business request on Jira ticket [NRM-440](https://collaboration.homeoffice.gov.uk/jira/browse/NRM-440)
- removed content from who-contact.md
n/a
=> NRM-440 content change

apps/nrm/behaviours/casework-submission.js, test/_unit/nrm/behaviours/casework-submission.spec.js
[NRM-466](https://collaboration.homeoffice.gov.uk/jira/browse/NRM-466) - Error in logs - Cannot set headers after they are sent to the client Cannot set headers after they are sent to the client
Refactored the saveValues method in the casework submission flow to fix a bug causing ERR_HTTP_HEADERS_SENT. This error occurred due to multiple invocations of next() in asynchronous paths, leading to Express attempting to send headers after the response was already sent.
The original implementation had multiple next() calls, especially within the deleteSessionData method and the SQS callback, which could result in Express throwing ERR_HTTP_HEADERS_SENT.
- Converted deleteSessionData to an async function and ensured it is properly awaited before calling next().
- Removed redundant next() calls to …
=> NRM-466: Logs error: ERR_HTTP_HEADERS_SENT
